spring:
  profiles:
    include: secret, oauth, storage, db, swagger
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 500
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  data:
    redis:
      lettuce:
        pool:
          min-idle: 0
          max-idle: 8
          max-active: 8
      port: 6379
      host: localhost